---
# Install HashiCorp Packer

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest
  become: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Import HashiCorp GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg
  become: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Add HashiCorp repository
  yum_repository:
    name: hashicorp
    description: HashiCorp YUM repo
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
  become: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Install latest packer
  yum:
    name: packer
    state: latest
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
