---
- name: update packages
  hosts: default
  become: yes

  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: yes

    - name: Remove leaf packages
      yum:
        autoremove: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: yum clean all
      command:
        cmd: yum clean all
        warn: no
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: yes
