---
- name: Update packages
  hosts: default
  become: true

  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: true

    - name: Remove leaf packages
      ansible.builtin.yum:
        autoremove: true
      when: ansible_facts['os_family'] == "RedHat"

    - name: Run yum clean all
      ansible.builtin.command:
        cmd: yum clean all
        warn: false
      when: ansible_facts['os_family'] == "RedHat"
      ignore_errors: true
